### ISSUE TITLE
AutoMigrate fails with error "invalid DDL" if a table with dash in name exists

### ISSUE THREAD

**Issue by cncal** [go-gorm/sqlite#102]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/488

## Description

As we can see in the playground，`AutoMigrate()` fails with error **`invalid DDL`** if a table with `-` in name exists.

**Comment by cncal** [comment]
I think [`tableRegexp`](https://github.com/go-gorm/sqlite/blob/64917553e84d5482e252c7a0c8f798fb672d7668/ddlmod.go#L17) and [`indexRegexp`](https://github.com/go-gorm/sqlite/blob/64917553e84d5482e252c7a0c8f798fb672d7668/ddlmod.go#L16) cannot recognize the table name with `-`  that causes this bug. If so, I'm glad to post a PR to fix it.

**Comment by a631807682** [comment]
Welcome to create a PR for it
