### ISSUE TITLE
Column should be nullable by default

### ISSUE THREAD

**Issue by JasonTangJun** [go-gorm/sqlite#107]
Please check [https://github.com/go-gorm/sqlite/blob/master/ddlmod.go#L29](url) at line 120. If a column is defined without "NOT NULL", it should be nullable by default. So line 120 needs to be modified as: 
NullableValue:    sql.NullBool{Bool: false, Valid: true}

**Comment by jinzhu** [comment]
the default value is already `	NullableValue:     sql.NullBool{Valid: true},`

which equals `NullableValue: sql.NullBool{Bool: false, Valid: true}`

**Comment by JasonTangJun** [comment]
If a column is defined without "NOT NULL" or "NULL",  it should be nullable by default. NullableValue: sql.NullBool{Bool: true, Valid: true}
