### ISSUE TITLE
Upgrade to mattn/go-sqlite3 v1.14.19

### ISSUE THREAD

**Issue by voltagex** [go-gorm/sqlite#177]
Please bump this dependency version

https://github.com/go-gorm/sqlite/blob/e64f7a58167c1bb6a60bf4ad6422e6d1b6111769/go.mod#L6

This fixes https://github.com/mattn/go-sqlite3/issues/1164 - can't build on Alpine 3.19 (?)

For anyone else hitting this, a _temporary workaround_ is to set `CGO_CFLAGS="-D_LARGEFILE64_SOURCE"`

**Comment by Racle** [comment]
Also manually changing go-sqlite3 in your `go.mod` file to correct versions seems to fix this 
```
github.com/mattn/go-sqlite3 v1.14.19 // indirect
```
