### ISSUE TITLE
Factory func Open

### ISSUE THREAD

**Issue by kiyonlin** [go-gorm/sqlite#2]
```
func Open(dsn string) gorm.Dialector {
	return &Dialector{DSN: dsn}
}
```

`Open` is the factory func of `sqlite` driver to generate a `gorm.Dialector`, but not open a db connection in actual. Maybe named `New` is more reasonable.

The same as other drivers.

**Comment by jinzhu** [comment]
Thank you for your feedback, I am thinking to use `Open` just accepts DSN, and the `New` method accepts more configurations than DSN like the MySQL driver https://github.com/go-gorm/mysql/blob/master/mysql.go#L31-L38

Any suggestion?

**Comment by kiyonlin** [comment]
That's great. Thank you for your job.
