### ISSUE TITLE
Add a way to override return value of Dialector.DefaultValueOf()

### ISSUE THREAD

**Issue by remyoster** [go-gorm/sqlite#34]
## Describe the feature
Add a way to override the return value of Dialector.DefaultValueOf()

## Motivation
For our project we use sqlite driver for the tests.
When we insert a default value with `gorm:default:null` it inserts DEFAULT instead of NULL. The field is a primary key and has AutoIncrement disabled because we are using snowflake.
We couldn't find any solution except by modifying the driver code which is not satisfying

**Comment by jinzhu** [comment]
can you create a PR on playground, don't get the idea.

btw, please recreate an issue on github.com/go-gorm/gorm with the PR link.

Thank you.

**Comment by schefi** [comment]
I had the same problem. The fact that SQLite does not understand the expression "DEFAULT" is even noted in the source code:
```
func (dialector Dialector) DefaultValueOf(field *schema.Field) clause.Expression {
	if field.AutoIncrement {
		return clause.Expr{SQL: "NULL"}
	}

	// doesn't work, will raise error
	return clause.Expr{SQL: "DEFAULT"}
} 
```
I would suggest the addition of a simple
```
	if field.HasDefaultValue {
		return clause.Expr{SQL: field.DefaultValue}
	}
```
before returning "DEFAULT". I have done this by reimplementing the Dialector interface in my project, which calls the sqlite.Dialector interface functions except with this small override before calling sqlite.DefaultValueOf()

It would be more efficient if this small change would be included upstream. 
Thank you!
