### ISSUE TITLE
SQLite doesn't create sqlite_sequence table

### ISSUE THREAD

**Issue by laeo** [go-gorm/sqlite#67]
## Description

Sample code below

 ```
type Message struct {
    ID int
}
```

I need set the initial auto increment value of message's id, and the sqlite's doc described the sqlite_sequence table. But when i try to manipulate it, i got an error, the table doesnt exists.

So i read the migrator's code, the `DataTypeOf()` method checks if the field is auto increment and not primary key field, migrator will generate proper statement to support auto increment.

But the ID field defaults handled as primary key, the problem seems can't fixed.

Gorm docs Conventions section say, we can use tag `primaryKey` to set other field as primary key, but migrator reports an error `table device has more than one primary key`.

How to fix it? Thanks for reply.

**Comment by jinzhu** [comment]
I don't get the question, can you please write a reproducible PR on `gorm-go/gorm` 

Thank you.

**Comment by orsinium** [comment]
[From the SQLite docs](https://renenyffenegger.ch/notes/development/databases/SQLite/internals/schema-objects/sqlite_sequence):

> In fact, it is created when the first table with an autoincrement column is created.

The `sqlite_sequence` table is not created unless you already have a table with an autoincrement field.
