### ISSUE TITLE
AutoMigrate 出现 duplicate column name 问题.

### ISSUE THREAD

**Issue by z2n** [go-gorm/sqlite#7]
## Description
 [HasColumn](https://github.com/go-gorm/sqlite/blob/5de74624667dcaa97dfc45aa7783ddf461bef94a/migrator.go#L65-L66) 的判断规则是:
```
"SELECT count(*) FROM sqlite_master WHERE type = ? AND tbl_name = ? AND (sql LIKE ? OR sql LIKE ? OR sql LIKE ?)",
"table", stmt.Table, `%"`+name+`" %`, `%`+name+` %`, "%`"+name+"`%",
```
但 Sqlite 的工具创建或修改表结构后的 `sqlite_master.sql` 格式并不一致, 造成 `hasColumn` 无法正确判断.
我遇到其中两个例外情况:

1. `column` 后使用 `tab` 而非 `space` 的.
```sql
CREATE TABLE posts (
  id	integer PRIMARY KEY, 
  created_at	datetime);
```
这个是在 mac 上的一个 sqlite gui 工具修改后的结果.

2.  使用 `[]` 作为分隔符.
```sql
CREATE TABLE [posts](
  [id] integer PRIMARY KEY, 
  [created_at] datetime);
```
这是 win 上 Sqlite Expert 修改后的结果.

**Comment by glebarez** [comment]
This PR breaks TestMigrateColumns test in GORM
