### ISSUE TITLE
Conversion to a Pure Golang implementation of SQLite

### ISSUE THREAD

**Issue by Ahbrown41** [go-gorm/sqlite#77]
## Describe the feature

The feature which I am happy to do a PR for is to remove the use of the existing CGO based SQLite implementation with a pure Golang based implementation [here](https://github.com/zombiezen/go-sqlite).

* https://github.com/zombiezen/go-sqlite

## Motivation

The CGO libraries are a HUGE pain with Windows machines and even other machines without the GCC binaries and specific settings.  It does not compile well in many scenarios.  This conversion appears to be solid and is a direct conversion of the C libraries of the original implementation.

**Comment by rittneje** [comment]
As I mentioned here, switching drivers is a breaking change. https://github.com/go-gorm/sqlite/issues/72#issuecomment-1005933250

**Comment by WinXaito** [comment]
Maybe create a new driver ? Like `sqlite-go` or `gosqlite`.

Because the CGO requirement is really akward

**Comment by glebarez** [comment]
have you tried https://github.com/glebarez/sqlite

**Comment by Arsen6331** [comment]
This can be done relatively easily using Go's tags to switch between drivers. modernc.org/sqlite contains a near drop-in replacement of the current driver. I've done this locally and will submit a PR shortly, regardless of if it gets merged.
