### ISSUE TITLE
Is it possible to use FTS5 module for full text search?

### ISSUE THREAD

**Issue by alexkmbk** [go-gorm/sqlite#78]
Here is the explanation of the mechanism - [https://www.sqlite.org/fts5.html](https://www.sqlite.org/fts5.html)

But somehow the FTS5 module should be installed. 
How to do it for the gorm SQLite driver?

**Comment by glebarez** [comment]
FTS5 is enabled in pure-go driver. You may try it for your purposes.

https://github.com/glebarez/sqlite

**Comment by ankitrgadiya** [comment]
This Sqlite driver internally uses [mattn/go-sqlite3](https://github.com/mattn/go-sqlite3) which supports FTS5. You can enable it using Build flags as per the [example](https://github.com/mattn/go-sqlite3#usage) here.
